// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toaiakpywqugljkftths.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvYWlha3B5d3F1Z2xqa2Z0dGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTI2NDgsImV4cCI6MjA2NjE2ODY0OH0.OqEtMjXELQWoe8ppP857XhgzrxvWV0hY0N_J1mFVsfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);